### ISSUE TITLE
User Dashboard Login/Sign Up Buttons 

### ISSUE THREAD

**Issue by tvonhake** [ethanmcneal/Streaks#60]
Login and Sign Up buttons show on dashboard even when signed in as a user
<img width="1334" alt="Screen Shot 2021-04-23 at 12 21 14 PM" src="https://user-images.githubusercontent.com/60283897/115914052-a47c6a00-a42e-11eb-9f5f-8f3a9615d376.png">

**Comment by tvonhake** [comment]
There is also an orange clickable on the left side inline with the "Creators" and "Login" links that does not do anything

**Comment by zyzzyxis** [comment]
dibs

**Comment by zyzzyxis** [comment]
Fixed!
