### ISSUE TITLE
Login/Registration UI Navigation

### ISSUE THREAD

**Issue by tvonhake** [ethanmcneal/Streaks#70]
When pages for Login/Registration are open, there are no options in the UI to navigate to other pages (home, about) in the site

**Comment by jimibue** [comment]
@tvonhake can you give me more clearification

**Comment by tvonhake** [comment]
@jimibue the only way to navigate away from login/registration forms is with back button in browser.

**Comment by zyzzyxis** [comment]
Dibs

**Comment by zyzzyxis** [comment]
fixed
